### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/ahocorasick/trie/Trie   

### ISSUE THREAD

**Issue by sunnywilliam** [promeG/TinyPinyin#54]
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/ahocorasick/trie/Trie

Caused by: java.lang.NoClassDefFoundError: org/ahocorasick/trie/Trie
        at com.github.promeg.pinyinhelper.Utils.dictsToTrie(Utils.java:22)
        at com.github.promeg.pinyinhelper.Pinyin.init(Pinyin.java:40)
        at com.tigerbrokers.alpha.bos.sap.util.PinyinUtil.normalizeToPinyin(PinyinUtil.java:33)
在A项目添加的maven依赖，B引用了A，B项目报错

**Comment by sunnywilliam** [comment]
依赖的信息
[INFO] |  \- com.github.promeg:tinypinyin:jar:2.0.3:compile
[INFO] |     \- org.ahocorasick:ahocorasick:jar:0.3.0:runtime
